03-02-2023 07:56:58 - _application - INFO - start - Application started
03-02-2023 07:58:07 - _application - INFO - stop - Application is stopping. This might take a moment.
03-02-2023 07:58:07 - _application - INFO - stop - Application.stop() complete
03-02-2023 07:58:09 - _application - INFO - start - Application started
03-02-2023 07:58:20 - _application - INFO - stop - Application is stopping. This might take a moment.
03-02-2023 07:58:20 - _application - INFO - stop - Application.stop() complete
03-02-2023 07:59:54 - _application - INFO - start - Application started
03-02-2023 08:04:43 - _application - INFO - stop - Application is stopping. This might take a moment.
03-02-2023 08:04:43 - _application - INFO - stop - Application.stop() complete
03-02-2023 08:13:22 - _application - INFO - start - Application started
03-02-2023 08:14:42 - _application - INFO - stop - Application is stopping. This might take a moment.
03-02-2023 08:14:42 - _application - INFO - stop - Application.stop() complete
03-02-2023 08:14:44 - executor - INFO - _welcome - Bot: colorhelper [@colorhelper_bot]
03-02-2023 08:14:44 - dispatcher - INFO - start_polling - Start polling.
03-02-2023 09:07:18 - dispatcher - INFO - stop_polling - Stop polling...
03-02-2023 09:07:18 - executor - WARNING - start_polling - Goodbye!
03-02-2023 09:07:22 - executor - INFO - _welcome - Bot: colorhelper [@colorhelper_bot]
03-02-2023 09:07:22 - dispatcher - INFO - start_polling - Start polling.
03-02-2023 09:07:52 - dispatcher - INFO - stop_polling - Stop polling...
03-02-2023 09:07:52 - executor - WARNING - start_polling - Goodbye!
03-02-2023 09:20:24 - executor - INFO - _welcome - Bot: colorhelper [@colorhelper_bot]
03-02-2023 09:20:24 - dispatcher - INFO - start_polling - Start polling.
03-02-2023 09:20:52 - base_events - ERROR - default_exception_handler - Task exception was never retrieved
future: <Task finished name='Task-37' coro=<Dispatcher._process_polling_updates() done, defined at C:\Users\alexa\OneDrive\Desktop\GB Python\tic_tac_toe_telegram\hello\Lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=KeyError('arrey')>
Traceback (most recent call last):
  File "C:\Users\alexa\OneDrive\Desktop\GB Python\tic_tac_toe_telegram\hello\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexa\OneDrive\Desktop\GB Python\tic_tac_toe_telegram\hello\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexa\OneDrive\Desktop\GB Python\tic_tac_toe_telegram\hello\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexa\OneDrive\Desktop\GB Python\tic_tac_toe_telegram\hello\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexa\OneDrive\Desktop\GB Python\tic_tac_toe_telegram\hello\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexa\OneDrive\Desktop\GB Python\tic_tac_toe_telegram\main.py", line 97, in tic_tac_toe_main
    arrey = data['arrey']
            ~~~~^^^^^^^^^
KeyError: 'arrey'
03-02-2023 09:21:48 - dispatcher - INFO - stop_polling - Stop polling...
03-02-2023 09:21:48 - executor - WARNING - start_polling - Goodbye!
03-02-2023 09:21:53 - executor - INFO - _welcome - Bot: colorhelper [@colorhelper_bot]
03-02-2023 09:21:53 - dispatcher - INFO - start_polling - Start polling.
03-02-2023 14:22:25 - dispatcher - INFO - stop_polling - Stop polling...
03-02-2023 14:22:25 - executor - WARNING - start_polling - Goodbye!
03-02-2023 14:22:30 - executor - INFO - _welcome - Bot: colorhelper [@colorhelper_bot]
03-02-2023 14:22:30 - dispatcher - INFO - start_polling - Start polling.
03-02-2023 14:41:10 - dispatcher - INFO - stop_polling - Stop polling...
03-02-2023 14:41:10 - executor - WARNING - start_polling - Goodbye!
03-02-2023 14:41:14 - executor - INFO - _welcome - Bot: colorhelper [@colorhelper_bot]
03-02-2023 14:41:14 - dispatcher - INFO - start_polling - Start polling.
03-02-2023 14:53:23 - dispatcher - INFO - stop_polling - Stop polling...
03-02-2023 14:53:23 - executor - WARNING - start_polling - Goodbye!
03-02-2023 14:53:28 - executor - INFO - _welcome - Bot: colorhelper [@colorhelper_bot]
03-02-2023 14:53:28 - dispatcher - INFO - start_polling - Start polling.
03-02-2023 14:53:42 - base_events - ERROR - default_exception_handler - Task exception was never retrieved
future: <Task finished name='Task-30' coro=<Dispatcher._process_polling_updates() done, defined at C:\Users\alexa\OneDrive\Desktop\GB Python\tic_tac_toe_telegram\hello\Lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=UnboundLocalError("cannot access local variable 'steps' where it is not associated with a value")>
Traceback (most recent call last):
  File "C:\Users\alexa\OneDrive\Desktop\GB Python\tic_tac_toe_telegram\hello\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexa\OneDrive\Desktop\GB Python\tic_tac_toe_telegram\hello\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexa\OneDrive\Desktop\GB Python\tic_tac_toe_telegram\hello\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexa\OneDrive\Desktop\GB Python\tic_tac_toe_telegram\hello\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexa\OneDrive\Desktop\GB Python\tic_tac_toe_telegram\hello\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexa\OneDrive\Desktop\GB Python\tic_tac_toe_telegram\main.py", line 126, in tic_tac_toe_main
    if (steps == 0 and isWin == True):
        ^^^^^
UnboundLocalError: cannot access local variable 'steps' where it is not associated with a value
03-02-2023 14:53:51 - base_events - ERROR - default_exception_handler - Task exception was never retrieved
future: <Task finished name='Task-39' coro=<Dispatcher._process_polling_updates() done, defined at C:\Users\alexa\OneDrive\Desktop\GB Python\tic_tac_toe_telegram\hello\Lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=UnboundLocalError("cannot access local variable 'steps' where it is not associated with a value")>
Traceback (most recent call last):
  File "C:\Users\alexa\OneDrive\Desktop\GB Python\tic_tac_toe_telegram\hello\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexa\OneDrive\Desktop\GB Python\tic_tac_toe_telegram\hello\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexa\OneDrive\Desktop\GB Python\tic_tac_toe_telegram\hello\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexa\OneDrive\Desktop\GB Python\tic_tac_toe_telegram\hello\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexa\OneDrive\Desktop\GB Python\tic_tac_toe_telegram\hello\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexa\OneDrive\Desktop\GB Python\tic_tac_toe_telegram\main.py", line 126, in tic_tac_toe_main
    if (steps == 0 and isWin == True):
        ^^^^^
UnboundLocalError: cannot access local variable 'steps' where it is not associated with a value
03-02-2023 14:54:24 - dispatcher - INFO - stop_polling - Stop polling...
03-02-2023 14:54:24 - executor - WARNING - start_polling - Goodbye!
03-02-2023 14:54:27 - executor - INFO - _welcome - Bot: colorhelper [@colorhelper_bot]
03-02-2023 14:54:27 - dispatcher - INFO - start_polling - Start polling.
03-02-2023 14:56:25 - dispatcher - INFO - stop_polling - Stop polling...
03-02-2023 14:56:25 - executor - WARNING - start_polling - Goodbye!
03-02-2023 14:56:30 - executor - INFO - _welcome - Bot: colorhelper [@colorhelper_bot]
03-02-2023 14:56:30 - dispatcher - INFO - start_polling - Start polling.
